{
    "name": "QMS",
    "summary": "ISO 9001 Quality Management System",
    "website": "https://www.tmcrosario.gob.ar",
    "version": "13.0.1.0.0",
    "author": "TMC Rosario, Odoo Community Association",
    "license": "AGPL-3",
    "depends": [],
    "data": [
        "security/qms_groups.xml",
        "security/ir.model.access.csv",
        "data/action_sequence.xml",
        "data/audit_sequence.xml",
        "data/non_conformity_sequence.xml",
        "data/opportunity_sequence.xml",
        "data/complaint_sequence.xml",
        "data/observation_sequence.xml",
        "data/action_stage.xml",
        "data/weakness_cause.xml",
        "data/finding_origin.xml",
        "data/finding_stage.xml",
        "views/policy_views.xml",
        "views/review_views.xml",
        "views/interested_party_views.xml",
        "views/resource_views.xml",
        "views/goal_views.xml",
        "views/goal_measurement_views.xml",
        "views/process_views.xml",
        "views/hazard_views.xml",
        "views/effectiveness_check_views.xml",
        "views/action_views.xml",
        "views/action_stage_views.xml",
        "views/audit_views.xml",
        "views/audit_verification_line_views.xml",
        "views/finding_milestone_views.xml",
        "views/weakness_cause_views.xml",
        "views/finding_origin_views.xml",
        "views/finding_stage_views.xml",
        "views/finding_views.xml",
        "views/non_conformity_views.xml",
        "views/observation_views.xml",
        "views/complaint_views.xml",
        "views/revision_by_direction_views.xml",
        "views/opportunity_views.xml",
        "views/indicator_views.xml",
        "views/indicator_measurement_views.xml",
        "views/document_views.xml",
        "views/procedure_views.xml",
        "views/version_views.xml",
        "views/instructive_views.xml",
        "views/registry_views.xml",
        "views/audit_evaluation_views.xml",
        "views/qms_menus.xml",
    ],
    "demo": [],
    "installable": True,
    "application": True,
    "qweb": [],
}
