{
    "name": "QMS",
    "summary": "ISO 9001 Quality Management System",
    "website": "https://www.tmcrosario.gob.ar",
    "version": "13.0.1.0.0",
    "author": "TMC Rosario, Odoo Community Association",
    "license": "AGPL-3",
    "depends": [],
    "data": [
        "security/qms_groups.xml",
        "security/ir.model.access.csv",
        "data/action_sequence.xml",
        "data/audit_sequence.xml",
        "data/non_conformity_sequence.xml",
        "data/opportunity_sequence.xml",
        "data/complaint_sequence.xml",
        "data/observation_sequence.xml",
        "data/action_stage.xml",
        "data/weakness_cause.xml",
        "data/finding_origin.xml",
        "data/finding_stage.xml",
        "views/policy.xml",
        "views/review.xml",
        "views/interested_party.xml",
        "views/resource.xml",
        "views/goal.xml",
        "views/goal_measurement.xml",
        "views/process.xml",
        "views/hazard.xml",
        "views/effectiveness_check.xml",
        "views/action.xml",
        "views/action_stage.xml",
        "views/audit.xml",
        "views/audit_verification_line.xml",
        "views/finding_milestone.xml",
        "views/weakness_cause.xml",
        "views/finding_origin.xml",
        "views/finding_stage.xml",
        "views/finding.xml",
        "views/non_conformity.xml",
        "views/observation.xml",
        "views/complaint.xml",
        "views/revision_by_direction.xml",
        "views/opportunity.xml",
        "views/indicator.xml",
        "views/indicator_measurement.xml",
        "views/document.xml",
        "views/procedure.xml",
        "views/version.xml",
        "views/instructive.xml",
        "views/registry.xml",
        "views/audit_evaluation.xml",
        "views/menu.xml",
    ],
    "demo": [],
    "installable": True,
    "application": True,
    "qweb": [],
}
